Feat/first draft
SelfKeyFoundation/airtable-proxy pull request #1
Opened 2018-09-12 15:42 UTC by rodrigopavezi

2018-09-12 16:24 UTC, sk91 requested changes

2018-09-12 16:24 UTC, sk91 commented on .gitignore
> +node_modules
please use full gitignore like in wallet

2018-09-12 16:24 UTC, sk91 commented on src/index.ts
> +      res.status(200).send({entities});
res.json is better here (that way no need to manually set json headers in responce)

also status 200 is set automatically

2018-09-12 16:24 UTC, sk91 commented on src/index.ts
> +    res.status(400).send('Missing Table Name Query Parameter');
should be json? reponse should be consistent

2018-09-12 16:24 UTC, sk91 commented on src/index.ts
> +      if (err) { console.error(err); return; }
I believe this will hang up your server, return without response

2018-09-12 16:24 UTC, sk91 commented on src/index.ts
> +  res.set("Access-Control-Allow-Origin", "*");
better to use cors middleware https://expressjs.com/en/resources/middleware/cors.html

here is how you can apply it:
https://codeburst.io/express-js-on-cloud-functions-for-firebase-86ed26f9144c

2018-09-12 16:27 UTC, sk91 requested changes

2018-09-12 16:27 UTC, sk91 commented on src/index.ts
> +  base(tableName).select().eachPage((recordsInPage: Array<any>, fetchNextPage: Function) => {
maybe extract thous callbacks to separate functions? will be cleaner that way

2018-09-12 16:43 UTC, rodrigopavezi commented on src/index.ts
> +  res.set("Access-Control-Allow-Origin", "*");
@sk91 I think I will stick with google docs on this https://cloud.google.com/functions/docs/writing/http. cheers

2018-09-12 19:34 UTC, rodrigopavezi commented
@sk91 made the changes please review again. Build it failing because the credentials for google cloud does not have permissions to deploy to cloud functions.

2018-09-13 10:12 UTC, sk91 approved these changes

2018-09-13 10:13 UTC, sk91 approved these changes
Looks Good! Cheers!

2018-09-14 07:45 UTC, merged